// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriviaGame.Data;

namespace TriviaGame.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TriviaGame.Data.Models.TriviaAnswer", b =>
                {
                    b.Property<int>("TriviaAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer");

                    b.Property<int>("Points");

                    b.Property<int?>("TriviaBoardId");

                    b.HasKey("TriviaAnswerId");

                    b.HasIndex("TriviaBoardId");

                    b.ToTable("TriviaAnswer");
                });

            modelBuilder.Entity("TriviaGame.Data.Models.TriviaBoard", b =>
                {
                    b.Property<int>("TriviaBoardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Question");

                    b.Property<int>("TotalPoints");

                    b.HasKey("TriviaBoardId");

                    b.ToTable("TriviaBoards");
                });

            modelBuilder.Entity("TriviaGame.Data.Models.TriviaAnswer", b =>
                {
                    b.HasOne("TriviaGame.Data.Models.TriviaBoard", "TriviaBoard")
                        .WithMany("Answers")
                        .HasForeignKey("TriviaBoardId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
